# Generated by Django 5.2.17 on 2026-09-21 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_fee_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('late_fee_charged', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('PICKED_UP', 'Picked Up'), ('RETURNED_SAFE', 'Returned Safe'), ('RETURNED_DAMAGED', 'Returned Damaged')], default='RESERVED', max_length=20)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='inventory.inventoryitem')),
                ('pickup_cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='inventory.partnercafe')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
