# Generated by Django 5.2.17 on 2026-10-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Reserved'), ('PICKED_UP', 'Picked Up'), ('RETURNED_SAFE', 'Returned Safe'), ('RETURNED_DAMAGED', 'Returned Damaged'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20),
        ),
    ]
