# Generated by Django 5.2.17 on 2026-09-21 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercafe',
            name='user',
            field=models.ForeignKey(help_text='The representative of the cafe.', on_delete=django.db.models.deletion.CASCADE, related_name='partner_cafes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.partnercafe'),
        ),
    ]
